### PR TITLE
feat: implement kafka user-defined source

### PR DESCRIPTION
**Pull request by KeranYang**
* Write a user-defined source version of Kafka.
* Tested with the pipeline template under the `./example` folder.
* Verified can see messages printed in log sink. Verified can see the `pending` metric on UI.

Screenshot 2023-09-28 at 11 49 22 AM

### CODE REVIEW

**Comment by vigith** [comment]
what is the performance difference?

**Comment by KeranYang** [comment]
> what is the performance difference?

WIP...

**Comment by KeranYang** [comment]
### Kafka Perf Test

I conducted a small local performance test and **didn't see major diffs.**

#### Testing Pipeline

I used the following pipeline template.

```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: kafka-source-e2e
spec:
  vertices:
    - name: in
      scale:
        min: 2
      volumes:
        - name: my-config-mount
          configMap:
            name: kafka-config-map
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-source/kafka-source-go:v0.1.8
            volumeMounts:
              - name: my-config-mount
                # /etc/config is the path where the Kafka source looks for the config file.
                mountPath: /etc/config
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: out
```

The Kafka server has two brokers. The input topic has two partitions. See Kafka configuration below.

```yaml
apiVersion: v1
data:
  # kafka-config.yaml is the config file that the Kafka source uses to connect to Kafka.
  kafka-config.yaml: |
    brokers:
      - 'keran-kafka-0.keran-kafka-headless.default.svc.cluster.local:9092'
      - 'keran-kafka-1.keran-kafka-headless.default.svc.cluster.local:9092'
    topic: input-topic-partition-debug
    consumergroupname: test-consumer-group-1
    tls: null
    config: ""
    sasl: null
kind: ConfigMap
metadata:
  name: kafka-config-map
```

I used the following Kafka command to send messages to the pipeline.

```bash
#!/bin/bash
while true
do
  kafka-producer-perf-test.sh --topic input-topic-partition-debug --num-records 9000 --producer-props bootstrap.servers=keran-kafka-0.keran-kafka-headless.default.svc.cluster.local:9092,keran-kafka-1.keran-kafka-headless.default.svc.cluster.local:9092 --throughput 9000 --record-size 100
done
```

`--num-records`: number of messages to produce.

`--throughput`: throttle maximum message throughput to *approximately* THROUGHPUT messages/sec.

`--record-size`: message size in bytes.

#### Using UDSource Kafka

`9000, 9000, 100`

Screenshot 2023-09-28 at 4 32 54 PM

#### Using built-in Kafka

`9000, 9000, 100`

Screenshot 2023-09-28 at 4 07 12 PM

**Comment by vigith** [comment]
How were the CPU and MEM usage?

**Comment by KeranYang** [comment]
> How were the CPU and MEM usage?

With the same testing setup as above. UDKafka consumes more CPU and MEM than built-in.

UDKafka


```
NAME                                       CPU(cores)   MEMORY(bytes)
kafka-source-e2e-in-0-f13gf                413m         144Mi           
kafka-source-e2e-in-1-7mztq                466m         145Mi
```

Built-in


```
NAME                                       CPU(cores)   MEMORY(bytes)
kafka-source-e2e-in-0-yfi3h                382m         84Mi            
kafka-source-e2e-in-1-k66bo                311m         83Mi
```

**Comment by KeranYang** [comment]
### per container consumption

Using a single Kafka source pod pipeline...

When switching from built-in to UDKafka, the numa container continues to consume a similar amount of CPU and MEM. The introduced udsource container consumes an extra 200+m CPU and 40+ Mi MEM.

Built-in

```
POD                    NAME                 CPU(cores)   MEMORY(bytes)
kafka-source-e2e       numa                 989m         95Mi 
```

UDKafka

```
POD                    NAME                 CPU(cores)   MEMORY(bytes)
kafka-source-e2e       numa                 954m         83Mi            
kafka-source-e2e       udsource             226m         47Mi 
```

cc: @vigith

**Comment by vigith** [comment]
> When switching from built-in to UDKafka, the numa container continues to consume a similar amount of CPU and MEM. The introduced udsource container consumes an extra 200+m CPU and 40+ Mi MEM.

That is a lot, what was the Kafka TPS? How long did we run the test?

**Comment by KeranYang** [comment]
> That is a lot, what was the Kafka TPS? How long did we run the test?

~2500 msgs/second. I waited until the source vertex processing rate was stable for 15 minutes before collecting the data.

**Pull request merged**
